/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {



    @Test public void testreadNdRandom (){
        String s =  "Marilyn Monroe";
        Quotes quotes = new Quotes();
        String path = "app/src/main/resources/test.json";
        quotes.read(path);
        quotes.random();


        String ss = quotes.getQuotes()[0].getAuthor();

        assertTrue(s==ss);


    }
}
