/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {
    public static void main(String[] args) {
        Api quotes = new Api();
        quotes.sendGetRequest();

    }
}
